repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgres
    namespace: mlops
    chart: ./postgres
    values:
      - postgres/values.yaml

  - name: airflow
    namespace: mlops
    chart: ./airflow
    values:
      - airflow/values.yaml

  - name: minio
    namespace: mlops
    chart: bitnami/minio
    version: 16.0.10
    values:
      - minio/values.yaml

  - name: mlflow
    namespace: mlops
    chart: ./mlflow
    values:
      - mlflow/values.yaml

  - name: api
    namespace: mlops
    chart: ./api
    values:
      - api/values.yaml

  - name: webapp
    namespace: mlops
    chart: ./webapp
    values:
      - webapp/values.yaml
