replicaCount: 1

serviceAccount:
  create: true

image:
  repository: minio/minio
  tag:        "latest"
  pullPolicy: IfNotPresent

# On ne touche pas à ENTRYPOINT, on ne passe QUE args :
args:
  - server
  - /data
  - "--console-address"
  - ":9001"

service:
  type: ClusterIP
  port:       9000
  targetPort: 9000

env:
  - name: MINIO_ROOT_USER
    value: minio
  - name: MINIO_ROOT_PASSWORD
    value: minio123

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /data

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - curl -f http://localhost:9000/minio/health/live || exit 1
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - curl -f http://localhost:9000/minio/health/live || exit 1
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

ingress:
  enabled: false

autoscaling:
  enabled: false
